<a href="https://colab.research.google.com/github/ponomarevaJV/PDA_SOL/blob/main/hw_2_numpy_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [1]:
import numpy as np
print ('Version:n',np.__version__,'\n')



Version:n 1.23.5 



2) Создать нулевой вектор размера 10

In [2]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [3]:
import numpy as np
x = np.full(7,7)
print(x)



[7 7 7 7 7 7 7]


4) Создать вектор заполненный четными числами от 10 до 100

In [4]:
import numpy as np
x= np.arange (10,100,2)
print (x)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [7]:
import numpy as np
x = np.random.rand(5)
print(x)
y = x[::-1]
print(y)

[0.46159967 0.62023895 0.38039715 0.48516809 0.25065509]
[0.25065509 0.48516809 0.38039715 0.62023895 0.46159967]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [8]:
import numpy as np
x = np.arange (9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [9]:
import numpy as np
x = np.eye (4)
print (x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [10]:
import numpy as np
x = np.diag([1, 2, 3, 4])
x[x ==0] = 7
print(x)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [11]:
import numpy as np
x = np.zeros((5,5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [12]:
import numpy as np
x = np.random.rand (10, 10)
print (x)
y = x - x.mean(axis=1, keepdims=True)
print(y)

[[0.29740432 0.10520882 0.4165201  0.34269295 0.03294529 0.63029827
  0.80710987 0.285157   0.31303914 0.28099383]
 [0.28412445 0.51715122 0.71707033 0.49498794 0.95680712 0.3038855
  0.56908446 0.82608482 0.6437121  0.10694234]
 [0.10489843 0.17599304 0.78521769 0.19271901 0.58972102 0.90268081
  0.30220627 0.16897252 0.70895499 0.3960304 ]
 [0.24281646 0.47075413 0.49090618 0.92014394 0.30135076 0.71072118
  0.55587155 0.17159407 0.3042134  0.16101777]
 [0.82818349 0.03958069 0.75518469 0.85596309 0.29291547 0.87670027
  0.82709425 0.15841355 0.26538206 0.00396961]
 [0.14515213 0.1127477  0.75843211 0.50311616 0.5355366  0.64455251
  0.65278174 0.1446351  0.96741435 0.866281  ]
 [0.68286428 0.8179517  0.62045291 0.82993022 0.97726814 0.33444356
  0.33306592 0.53503058 0.22079285 0.47638965]
 [0.19849932 0.91529002 0.7827386  0.96799879 0.16228935 0.5495787
  0.16992722 0.64151875 0.89191957 0.02294842]
 [0.77399624 0.64357172 0.3938338  0.33947004 0.14757614 0.50263603
  0.67089399 0

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [13]:
import numpy as np
x = np.random.rand (10, 10)
print (x)
y = np.median(x, axis=0)
b= x-y
print (b)

[[0.5214202  0.63473732 0.55975908 0.82758995 0.51768382 0.42928132
  0.08365973 0.86865979 0.78162645 0.2984906 ]
 [0.97994907 0.83937808 0.78516502 0.766775   0.46846727 0.57912101
  0.42407584 0.01530223 0.22053065 0.89035419]
 [0.93761386 0.13084212 0.80110035 0.5219866  0.00945934 0.19240385
  0.75165214 0.257652   0.81447356 0.41153041]
 [0.40111637 0.57785062 0.8458534  0.56520546 0.80744151 0.4937092
  0.83503724 0.30603601 0.60162345 0.17162151]
 [0.38934961 0.76950124 0.30951223 0.05090189 0.37212259 0.25083793
  0.8263372  0.61635668 0.46663325 0.91929157]
 [0.92440234 0.81315452 0.24907768 0.93746807 0.44363379 0.09922093
  0.75126534 0.89693463 0.70755416 0.12113444]
 [0.21056394 0.6821636  0.95157647 0.37925368 0.63511342 0.74743859
  0.01875444 0.03955333 0.90643375 0.88913482]
 [0.29511536 0.31296733 0.79651333 0.44521293 0.34903963 0.7683845
  0.26551025 0.39558184 0.34308334 0.29069734]
 [0.97396567 0.3173879  0.65834626 0.84427189 0.41477176 0.52403745
  0.5435208  0

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [14]:
import numpy as np
x = np.random.rand (5, 5)
print (x)
a = np.amin(x, axis=1)
b = np.amax(x, axis=0)
c = np.vstack ([a,b])
d = np.vstack ((x,c))
print(d)

[[0.64089725 0.96483912 0.33817926 0.1285531  0.66535742]
 [0.86086805 0.14309335 0.23927697 0.43542013 0.00293862]
 [0.20108579 0.61751393 0.84295859 0.16274554 0.12602488]
 [0.65656875 0.11515992 0.93682818 0.74710314 0.70069247]
 [0.86160712 0.37297534 0.74261828 0.74306238 0.12024866]]
[[0.64089725 0.96483912 0.33817926 0.1285531  0.66535742]
 [0.86086805 0.14309335 0.23927697 0.43542013 0.00293862]
 [0.20108579 0.61751393 0.84295859 0.16274554 0.12602488]
 [0.65656875 0.11515992 0.93682818 0.74710314 0.70069247]
 [0.86160712 0.37297534 0.74261828 0.74306238 0.12024866]
 [0.1285531  0.00293862 0.12602488 0.11515992 0.12024866]
 [0.86160712 0.96483912 0.93682818 0.74710314 0.70069247]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [18]:
import numpy as np
x= np.arange (1,51)
print (x)
a = [x for x in x if x % 2 == 0]
print(a)
b = [x for x in x if x % 2 != 0]
print(b)
y=np.arange (1,51,2)
print(y)
z = np.arange (2,51,2)
print(z)
c= y.reshape((5,5))
print(c)
d = z.reshape((5,5))
print(d)
g = np.matmul(d, c)
print(g)
p = np.linalg.inv(g) -  матрицу невозможно найти, так как детерминант матрицы равен нулю (Singular matrix)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
[[ 830  890  950 1010 1070]
 [1880 2040 2200 2360 2520]
 [2930 3190 3450 3710 3970]
 [3980 4340 4700 5060 5420]
 [5030 5490 5950 6410 6870]]


LinAlgError: ignored

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [15]:
import numpy as np
x = np.zeros((8, 8))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
